project:
  type: website
  output-dir: docs

website:
  title: "CODEMAP"
  site-url: "https://codemap-nl.github.io/codemap-nl-website/"
  repo-url: "https://github.com/codemap-nl/codemap-nl-website"
  repo-actions: [edit, issue]
  # description: "Strengthening the field of infectious disease modelling and data analysis in the Netherlands in a sustainable way."
  favicon: images/favicon.ico
  
  navbar:
    background: "rgba(255, 255, 255, 0.95)"
    foreground: "#333"
    logo: "images/logos/EMDA_logo.png"
    logo-alt: "CODEMAP Logo"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: members/index.qmd
        text: Members
      - href: events/index.qmd
        text: Events
      - href: projects/index.qmd
        text: Projects        
      - href: resources/index.qmd
        text: Resources
      - href: news/index.qmd
        text: News
    
    tools:
      - icon: github
        href: https://github.com/codemap-nl
      - icon: linkedin
        href: https://www.linkedin.com/groups/13094435/
      - icon: globe
        href: https://www.rivm.nl/infectieziektebestrijding/modelleren/collaborative-platform-en
      - icon: envelope
        href: mailto:collabforepidemodatanalytics@rivm.nl
  page-footer:
    left: |
      Â© 2025 CODEMAP-NL. Licensed under Creative Commons 
      Attribution-NonCommercial 4.0 International License.
    right:
      - icon: github
        href: https://github.com/codemap-nl
      - icon: linkedin
        href: https://www.linkedin.com/groups/13094435/
      - icon: globe
        href: https://www.rivm.nl/infectieziektebestrijding/modelleren/collaborative-platform-en
      - icon: envelope
        href: mailto:collabforepidemodatanalytics@rivm.nl

format:
  html:
    theme: cosmo
    css: _includes/styles.css
    #include-after-body: _includes/scripts.html
    toc: false
    smooth-scroll: true
    link-external-newwindow: true

execute:
  freeze: auto

